export const radiationRecordsInitialState = {
  inhalationRecords: [
    {
      element: {
        cas: '7440-48-4',
        code: 134,
        formula: 'Со',
        hydrocarbon: 0,
        measure: 'мг/м³',
        name: 'Кобальт (Кобальт металлический)',
        rigid: 1,
        short_name: 'Кобальт',
        voc: 0,
      },
      inhalationIntensity: 1,
      volumetricActivity: 1,
    },
    {
      element: {
        cas: '12185-10-3',
        code: 339,
        formula: 'Р',
        hydrocarbon: 0,
        measure: 'мг/м3',
        name: 'Фосфор білий',
        rigid: 1,
        short_name: 'фосфор',
        voc: 0,
      },
      inhalationIntensity: 1000,
      volumetricActivity: 1,
    },
  ],
  waterRecords: [
    {
      element: {
        cas: '7440-48-4',
        code: 134,
        formula: 'Со',
        hydrocarbon: 0,
        measure: 'мг/м³',
        name: 'Кобальт (Кобальт металлический)',
        rigid: 1,
        short_name: 'Кобальт',
        voc: 0,
      },
      waterPerYear: 10,
      volumetricActivity: 2,
    },
    {
      element: {
        cas: '12185-10-3',
        code: 339,
        formula: 'Р',
        hydrocarbon: 0,
        measure: 'мг/м3',
        name: 'Фосфор білий',
        rigid: 1,
        short_name: 'фосфор',
        voc: 0,
      },
      waterPerYear: 2,
      volumetricActivity: 1000,
    },
  ],
  productRecords: [
    {
      element: {
        cas: '7440-48-4',
        code: 134,
        formula: 'Со',
        hydrocarbon: 0,
        measure: 'мг/м³',
        name: 'Кобальт (Кобальт металлический)',
        rigid: 1,
        short_name: 'Кобальт',
        voc: 0,
      },
      productPerYear: 3,
      volumetricActivity: 1,
      radionuclideConsumptionFactor: 3,
    },
    {
      element: {
        cas: '12185-10-3',
        code: 339,
        formula: 'Р',
        hydrocarbon: 0,
        measure: 'мг/м3',
        name: 'Фосфор білий',
        rigid: 1,
        short_name: 'фосфор',
        voc: 0,
      },
      productPerYear: 3,
      volumetricActivity: 100000,
      radionuclideConsumptionFactor: 3,
    },
  ],
  soilRecords: [
    {
      element: {
        cas: '7440-48-4',
        code: 134,
        formula: 'Со',
        hydrocarbon: 0,
        measure: 'мг/м³',
        name: 'Кобальт (Кобальт металлический)',
        rigid: 1,
        short_name: 'Кобальт',
        voc: 0,
      },
      volumetricActivity: 100,
      soilAbsorptionRate: 0.12,
      duration: 365,
    },
    {
      element: {
        cas: '12185-10-3',
        code: 339,
        formula: 'Р',
        hydrocarbon: 0,
        measure: 'мг/м3',
        name: 'Фосфор білий',
        rigid: 1,
        short_name: 'фосфор',
        voc: 0,
      },
      volumetricActivity: 1000000,
      soilAbsorptionRate: 0.16,
      duration: 367,
    },
  ],
};
